version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: eg0rmaffin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - my-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
